{
 "title": "Panele",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Produkcja dzienna KW",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "panele_generationcurrentday>0" }
   ]
  },
  {
   "title": "Produkcja od początku założenia KW",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "panele_lifetimegeneration>0" }
   ]
  },
  {
   "title": "Ostatni odczyt W",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "panele_LastSystemPower>0" }
   ]
  },
  {
   "title": "Napiecie",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "V" }
   ],
   "targets": [
    {
     "expr": "panele_Voltage{Inverter=~\".*\",panel=\"1\"} > 0",
     "legendFormat": "{{Inverter}}"
    }
   ]
  },
  {
   "title": "temperatura",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "panele_Temp", "legendFormat": "falownik nr - {{Inverter}}" }
   ]
  },
  {
   "title": "MOC wat",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "W" }
   ],
   "targets": [
    { "expr": "panele_Power >0", "legendFormat": "{{Inverter}} - {{panel}}" }
   ]
  }
 ]
}